# Copyright (c) TuringCSTC. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
# Server HTTP port.
server:
  port: 8080

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
# LOGGING
logging:
  # Location of the log file. For instance, `/var/log`.
  path: logs
  file: ${logging.path}/nebula-dev.log
  # Maximum of archive log files to keep. default 0 days
  file.max-history: 0
  # Maximum log file size. default 10MB
  file. max-size: 10MB
  # 项目依赖的library日志级别在logback-spring-dev.xml中设置。
  config: classpath:config/logback-spring-dev.xml
  # 项目package的日志级别在此设置。
  # logger level : TRACE, DEBUG, INFO, WARN, ERROR, FATAL
  Level:
    root: INFO
    nebula.application: INFO

# BANNER
# http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Standard&t=Nebula-Dev
spring:
  banner:
    location: classpath:banner/banner-dev.txt
