# Copyright (c) TuringCSTC. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

# ======================================================================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
# ======================================================================================================================
spring:
  application:
    name: nebula
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by gradle when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    # dev or prod
    active: #spring.profiles.active#
  jmx:
    # Expose management beans to the JMX domain.
    enabled: false
  data:
    jpa:
      repositories:
        # Support for Hibernate asynchronous boot. Hibernate will start in a separate thread, while other applications start up in parallel.
        bootstrap-mode: deferred
  jpa:
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false

#    properties:
#      hibernate.jdbc.time_zone: UTC
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        implicit-strategy:  org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'prometheus', 'threaddump']


server:
  servlet:
    session:
      cookie:
        # JS scripts, applets, will not be able to read the cookie information, which can effectively prevent XSS attacks.
        http-only: true

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================
jhipster:
  clientApp:
    name: 'jhipsterSampleApplicationApp'
  # By default CORS is disabled. Uncomment to enable.
  # cors:
  #     allowed-origins: "*"
  #     allowed-methods: "*"
  #     allowed-headers: "*"
  #     exposed-headers: "Authorization,Link,X-Total-Count"
  #     allow-credentials: true
  #     max-age: 1800
  mail:
    from: jhipsterSampleApplication@localhost
  swagger:
    default-include-pattern: /api/.*
    title: jhipsterSampleApplication API
    description: jhipsterSampleApplication API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url:

  # =============================================================================
  # Application specific properties
  # Add your own application properties here, see the ApplicationProperties class
  # =============================================================================
  # application:
  # For demo
#  servers:
#    - dev.example.com
#    - another.example.com