# Copyright (c) TuringCSTC. All rights reserved.
# Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
# Server HTTP port.
server:
  port: 8080

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
# LOGGING
logging:
  # Location of the log file. For instance, `/var/log`.
  path: logs
  file: ${logging.path}/nebula-dev.log
  # Maximum of archive log files to keep. default 0 days to keep
  file.max-history: 0
  # Maximum log file size. default each archived file, size max 10MB
  file.max-size: 10MB
  # 项目依赖的library日志级别在logback-spring-dev.xml中设置。
  config: classpath:config/logback-spring-dev.xml
  # 项目package的日志级别在此设置。
  # logger level : TRACE, DEBUG, INFO, WARN, ERROR, FATAL
  Level:
    root: INFO
    nebula.application: INFO

# BANNER
# http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Standard&t=Nebula-Dev
spring:
  banner:
    location: classpath:banner/banner-dev.txt

  # DATASOURCE
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:NebulaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      # Path at which the console is available.http://localhost:8080/h2-console
      path: /h2-console
  liquibase:
    # Change log configuration path.
    change-log: classpath:/db/h2/changelog/db.changelog-master.xml

  # ----------------------------------------
  # DEVTOOLS PROPERTIES
  # ----------------------------------------
  devtools:
    # Whether to enable automatic restart. default = true
    restart.enabled: true

